Support creating ItemCollections in Transaction Extension
stac-utils/stac-fastapi-pgstac pull request #35
Opened 2023-05-11 17:02 UTC by mmcfarland

**Description:**

Implements "create ItemCollection" via the Transaction extension and provides additional validation and behavior on ids when creating Items or ItemCollections. I'll note that the api spec indicates percent encoded characters are _discouraged_, but this change makes them invalid for this backend. That's an opinioned change, and I'm willing to walk it back to a subset (like just "/") if that flexibility is desired.

See: https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#item-ids
See: https://github.com/radiantearth/stac-api-spec/blob/master/ogcapi-features/extensions/transaction/README.md#methods

Fixes: https://github.com/stac-utils/stac-fastapi-pgstac/issues/23

**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [x] Tests pass (run `make test`)
- [x] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/stac-fastapi/blob/main/CHANGES.md).

2023-05-11 17:02 UTC, mmcfarland commented
_Note_: This is draft until https://github.com/stac-utils/stac-fastapi/pull/574 is merged, as tests here will fail without it.

2023-05-15 14:01 UTC, gadomski requested changes

2023-05-15 19:58 UTC, mmcfarland commented on stac_fastapi/pgstac/transactions.py
> +    ) -> Optional[Union[stac_types.Item, Response]]:
Based on the [language in the spec](https://github.com/radiantearth/stac-api-spec/blob/master/ogcapi-features/extensions/transaction/README.md#post), it seems the best alignment would be to always return None, then. But it does appear to allow for Item or None depending on the request body type.

When `Item` (emphasis mine)
> _May_ return the content of the newly added resource for a successful operation.

When `ItemCollection`
_unspecified_

The [SQLAlchemy implementation](https://github.com/stac-utils/stac-fastapi-sqlalchemy/blob/main/stac_fastapi/sqlalchemy/transactions.py#L51) does the Item/None response as well.

I think your discomfort + the spec also saying an Item should use a location header pushes me towards always having an empty body, but adding that location header. That a bit of a breaking change (even in many unit tests!) -- are you comfortable with that?

2023-05-15 21:30 UTC, gadomski commented on stac_fastapi/pgstac/transactions.py
> +    ) -> Optional[Union[stac_types.Item, Response]]:
Hm, good point. It's probably not worth breaking just to make things feel nicer ... so let's keep it as is. Thanks for looking into that.

2023-05-15 21:30 UTC, gadomski approved these changes

2023-05-16 14:35 UTC, mmcfarland commented
@gadomski I added some commits that should address your comments, thanks for the feedback. I had started down the path of response unification, but then realized the extent to which it was a meaningful breaking changed, and walked it back in a subsequent commit. Tests pass locally against stac-fastapi `main`, so I'll leave this in draft until the next stac-fastapi release.

2023-05-17 15:36 UTC, gadomski approved these changes

2023-05-17 15:49 UTC, merged